name: docker-push
on:
  push:		
     branches:		
     - master		
     tags:		
       - v1.*
  pull_request:
    branches-ignore:
    - release

jobs:
  docker-build:
    name: build-docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker-build
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/github-self-hosted
        tag_with_ref: true
        push: true
